version: "3.8"

services:
  elasticsearch_slstats:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: ElasticsearchSLStats
    ports:
      - 9622:9200
    environment:
      - discovery.type=single-node
    volumes:
      - esdatavol:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 1s
      timeout: 10s
      retries: 100
      start_period: 3s
    networks:
      - elasticsearch-net

  mongo_slstats:
    image: mongo:5
    container_name: MongoSLStats
    ports:
     - 27017:27017
    volumes:
     - mongodatavol:/data/db

  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    volumes:
      - ./kafka-properties:/properties


  elasticsearch_raw:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: ElasticsearchSLRawStats
    ports:
      - 9722:9200
    environment:
      - discovery.type=single-node
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 1s
      timeout: 10s
      retries: 100
      start_period: 3s
    networks:
      - elasticsearch-net

# these volumes are stored at \\wsl.localhost\rancher-desktop-data\var\lib\docker\volumes\savelife-stats_{name}
volumes:
  esdatavol:
    external: false
  mongodatavol:
    external: false

networks:
  elasticsearch-net: